### ISSUE TITLE
Python Requests Lib Tor Connection Script with IP Change Verification 🌐🔒

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#11]
**Objective**:

Create a Python script or module that establishes a connection over the Tor network, ensuring anonymity, and includes functionality to verify that the IP address has changed.

Mainly this module should redirect requests made through the Python requests library over the Tor network, Once tor is set up through this script any requests made from the same script will automatically redirected.

**Features**:

1. **Tor Connection Setup**:
   - Implement a function to establish a connection through the Tor network, ensuring anonymous browsing.

2. **IP Change Verification**:
   - Develop a mechanism to confirm that the IP address has changed after connecting through Tor.
   - well you can use Tor's official website that has information, whether you are connected to Tor or not. https://check.torproject.org/
   - Or you can simply fetch IP info from any website ex: https://httpbin.org/ip

3. **User-Friendly Output**:
   - Provide clear feedback on the Tor connection status and IP address verification.
   - Simple one-line logging is enough for user.

**Example Usage**:

```python
# Example usage of the Tor connection script
import tor_connector

# Connect to Tor network
tor_connector.connect()

# Check if the IP address has changed
ip_changed = tor_connector.verify_ip_change()

if ip_changed:
    print("IP address has changed.")
else:
    print("IP address remains the same.")
```
**Difficulty**: Beginner/Intermediate

**Tags**: Python, Tor Network, Anonymity, IP Verification, Security

**Additional Information**:
- Familiarity with the Tor network, network protocols, and Python programming is recommended for contributors interested in this task.
- Feel free to ask any doubts or any guidance.

**Comment by Zhreyu** [comment]
hey can I work  on this?

**Comment by bhargavnova** [comment]
Sure!!

**Comment by bhargavnova** [comment]
Thanks for your contribution :)
