### ISSUE TITLE
URL Validator Python Script 🌐✅

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#14]
**Objective**:
Develop a Python script that checks if a given URL is valid and accessible. This tool will help users verify the correctness of URLs.

**Features**:

1. **URL Validation**:
   - Implement a function to validate the format and structure of a URL.
   - for example: https://example.com -> is valid , htt://data.com -> invalid

2. **Accessibility Check**:
   - Verify if the URL is reachable and returns a valid HTTP response.

3. **User-Friendly Output**:
   - Provide clear feedback on the validity and accessibility of the URL.

**Example Usage**:

```python
# Example usage of the URL validator script
import url_validator

url = "https://www.example.com"
is_valid, is_accessible = url_validator.validate(url)

if is_valid:
    print("The URL is valid.")
    
    if is_accessible:
        print("The URL is accessible.")
    else:
        print("The URL is not accessible.")
else:
    print("The URL is not valid.")
```

**Difficulty**: Beginner/Intermediate
**Tags**: Python, URL Validation, Accessibility, HTTP Requests

**Additional Information**:
- Familiarity with URL structure and basic Python programming is recommended for contributors interested in this task.
- Consider using the `requests` library for making HTTP requests to verify URL accessibility.

**Comment by chankruze** [comment]
I am working on it. @bhargavnova Assign it to me.

**Comment by bhargavnova** [comment]
Sure!!

**Comment by nexuspy** [comment]
can I work On this?

**Comment by bhargavnova** [comment]
Hi! @chankruze ,
I accidentally merged your request, but please remove the example folder, move that code into same .py file, and open the request again.

**Comment by chankruze** [comment]
Sure

**Comment by bhargavnova** [comment]
@nexuspy ,
You can find any other already open issues,
or if you have anything in mind you can submit that.
