### ISSUE TITLE
Find runnning python scripts on system

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#2]
**TIP**: psutil (library of python)
- Use a class-based approach which can contain the below methods or more.
- detect and return pid of all running Python script on the system,
- a function that can take pid of a process and kill that.
- a function that can just log all the running script basic info (pid, script path...)

**Comment by Siddharth9890** [comment]
@bhargavnova hey i can try this

**Comment by bhargavnova** [comment]
Sure!!

**Comment by TanyaKansal** [comment]
Hey can I try this

**Comment by bhargavnova** [comment]
Hi @TanyaKansal , I have already assigned this to @Siddharth9890 ,
So you can check out other issues,
or you can submit something of your own,

Thanks : )
Happy Coding!!

**Comment by bhargavnova** [comment]
Thank you for your contribution @Siddharth9890,

Once again, thank you for your exceptional work. We're looking forward to achieving even greater heights together!
Warm regards,
