### ISSUE TITLE
Create a Python Script for GitHub Interaction

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#3]
**Issue Description**:

This script should demonstrate basic interactions like creating issues, fetching repository details, or any other functionality you find interesting.

**Requirements**:

1. The script should be written in Python.
2. It should utilize the GitHub API for interaction.
3. Choose any aspect of GitHub interaction that you find useful or intriguing.

**Submission Guidelines**:

1. Fork this repository.
2. Create a Python script named `github_interaction.py`.
3. Write clean and well-commented code.
4. Ensure the script is capable of performing basic GitHub interactions.
5. Submit a pull request with your code.

**Note**: Feel free to explore the [GitHub API documentation](https://docs.github.com/en/rest) for inspiration and guidance.

**Difficulty**: Beginner/Intermediate

**Tags**: Python, GitHub API, Scripting

**Comment by VishalS-HK** [comment]
Hello there!! Can I be assigned this issue?

**Comment by bhargavnova** [comment]
Sure!!

**Comment by bhargavnova** [comment]
# Updated Contribution Guidelines

Dear @VishalS-HK ,

I hope this message finds you well!

I wanted to take a moment to inform you about some updates I've made to contribution guidelines. Your valuable contribution will be been instrumental in the success of this repo project, and I want to ensure that we both are on the same page moving forward.

The updated guidelines can be found [here](https://github.com/bhargavnova/python-helper-modules#contributing-guidelines). I kindly request you to review them at your earliest convenience.

If you have any questions or need further clarification on any points, please don't hesitate to reach out. Your expertise and insights are highly valued, and I greatly appreciate your continued dedication to this repo.

Thank you once again for all your hard work and contributions. I look forward to collaborating with you on future endeavors!
Warm regards,

**Comment by bhargavnova** [comment]
Hi @VishalS-HK ,
Thank you for your contribution, :)
you can look for other open issues or you can also submit your own code.

Thanks :)
Happy Coding!
