### ISSUE TITLE
Python CSV CRUD Module

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#32]
### Objective

Develop a Python module that allows users to perform basic CRUD (Create, Read, Update, Delete) operations on CSV (Comma Separated Values) files. This module will provide a convenient interface for managing data in CSV files using Python.

### Features

- **Create**: Implement functionality to add new records to a CSV file.
- **Read**: Enable users to view the content of a CSV file.
- **Update**: Provide the ability to modify existing records in the CSV file.
- **Delete**: Allow users to remove specific records from the CSV file.

### Example Usage

```python
import csv_crud

# Create a new record
csv_crud.create_record('data.csv', {'Name': 'John Doe', 'Email': 'john@example.com', 'Age': 30})

# Read the CSV file
data = csv_crud.read_csv('data.csv')
print(data)

# Update a record
csv_crud.update_record('data.csv', 1, {'Name': 'Jane Doe', 'Email': 'jane@example.com', 'Age': 35})

# Delete a record
csv_crud.delete_record('data.csv', 2)
```
`Difficulty`: Beginner/Intermediate

`Tags`: Python, CSV, CRUD Operations

### Additional Information
- The module should handle cases where the CSV file does not exist or is empty.
- Ensure that the module provides clear error messages in case of any issues with file operations or data manipulation. 

### Contribution Guidelines
The updated guidelines can be found [here](https://github.com/bhargavnova/python-helper-modules#contributing-guidelines).

### Note:
- `folder_name`: csv_curd_manage
- `script_name`: csv_curd_manage

**Comment by bhargavnova** [comment]
`Folder Name` : csv_curd_handler
`Script Name` : csv_curd_handler

**Comment by k0msenapati** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by bhargavnova** [comment]
Sure @kom-senapati ,
Thanks for picking this up!

Happy Coding!

**Comment by bhargavnova** [comment]
Hi @kom-senapati ,
Thanks for your contribution,

You can take a look at other open issues or, you can also submit one of your own code/ideas.

Thanks :)
Happy coding!
