### ISSUE TITLE
Extract JSON Data from HTML `<script>` Tags

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#35]
### Objective

Develop a Python script or module that extracts JSON (JavaScript Object Notation) data embedded within HTML `<script>` tags. This tool will provide a convenient way to parse and retrieve JSON data from web pages for further processing or analysis.

### Features

- **Extract JSON Data**: Implement functionality to identify and extract JSON objects embedded within `<script>` tags in HTML documents.
- **Handle Multiple Instances**: Ensure the script can handle cases where there are multiple `<script>` tags containing JSON data on a single page.
- **Option for Formatting**: Provide an option to format and prettify the extracted JSON data for better readability.

### Example Usage

```python
import json_extractor

# Extract JSON data from an HTML file
json_data = json_extractor.extract_from_html('sample.html')

# Extract JSON data from a URL
json_data = json_extractor.extract_from_url('https://example.com')
```
`Difficulty`: Intermediate/Advanced

`Tags`: Python, JSON, HTML, Web Scraping, Data Extraction

### Additional Information
- Consider using libraries like beautifulsoup4 for parsing HTML content and JSON for handling JSON data in Python.
- Ensure that the script provides informative error messages in case of invalid HTML input or other issues during the extraction process.

### Contribution Guidelines
The updated guidelines can be found [here](https://github.com/bhargavnova/python-helper-modules#contributing-guidelines).

### Note:
- `folder_name`: html_to_json
- `script_name`: html_to_json

**Comment by Ninnjah** [comment]
i'll take this

**Comment by bhargavnova** [comment]
Sure! @Ninnjah,
Thanks for picking this up.
Just keep in my the Guidelines.

Happy Coding!
