### ISSUE TITLE
Random Password Generator Script/Module

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#37]
### Objective

Develop a Python script or module that generates random passwords based on user-defined criteria. This tool will allow users to specify the length of the password, include or exclude certain characters, and customize other parameters to generate secure and customizable passwords.

### Features

- **Customizable Length**: Allow users to specify the desired length of the generated password.

- **Character Inclusion/Exclusion**:
  - Provide options for users to include or exclude specific characters or character sets (e.g., uppercase, lowercase, numbers, symbols).

- **Secure Randomization**:
  - Implement a secure randomization algorithm to ensure password strength.

- **Generate Multiple Passwords**:
  - Allow users to generate a batch of random passwords at once.

### Example Usage

```python
import password_generator

# Generate a random password with default settings
default_password = password_generator.generate_password()

# Generate a random password with custom length and included characters
custom_password = password_generator.generate_password(length=12, include_chars='Aa1@')

# Generate multiple passwords at once
batch_passwords = password_generator.generate_batch_passwords(5, length=10, include_chars='Aa1@')
```
`Difficulty`: Beginner/Intermediate

`Tags`: Python, Password Generation, Security, Customization

### Additional Information
- Ensure that the generated passwords are sufficiently strong and meet standard security requirements.
- Provide user-friendly error messages for any invalid input or edge cases.

### Contribution Guidelines
The updated guidelines can be found [here](https://github.com/bhargavnova/python-helper-modules#contributing-guidelines).

### Note:
- `folder_name`: generate_password
- `script_name`: generate_password

**Comment by AaroneGeorge** [comment]
hey, can I pick up this issue?

**Comment by bhargavnova** [comment]
Sure!!
Happy to help you :)

Just keep in mind the Guidelines.

**Comment by aecuto** [comment]
done :)

**Comment by bhargavnova** [comment]
Dear @aecuto,
I have already assigned this issue to @AaroneGeorge , he might started working on that,
so I won't be able to accept your request this time, you both can collaborate also, to improve the code, and add more features, so let's see how @AaroneGeorge does, the job, maybe I can combine both scripts.

Or you can work on any other open issues, or you can submit something of your own.
or wait a little bit I will be adding more issues on the repo as I get some time.

Thanks Hope you understand.
Happy Coding!!

**Comment by aecuto** [comment]
anything suggest @AaroneGeorge feel free to review at #43

**Comment by AaroneGeorge** [comment]
ok

**Comment by bhargavnova** [comment]
@aecuto , I have reviewed @AaroneGeorge code,
I think i will have to close your request, you can check his code, and if you want to add any additional feature, you can open a pull request.
Happy Coding!
