### ISSUE TITLE
 Merge Multiple CSV Files Script/Module

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#39]
### Objective

Develop a Python script or module that allows users to merge multiple CSV (Comma Separated Values) files into a single combined CSV file. This tool will provide a convenient way to aggregate data from multiple sources and create a unified dataset.

### Features

- **CSV File Selection**: Allow users to specify a list of CSV files to be merged.

- **Column Mapping and Handling**: Provide options to handle cases where the CSV files have varying columns, such as skipping or filling missing values.

- **Customized Output File Name**: Allow users to specify a custom name for the merged CSV file.

- **Handle Large Datasets**: Ensure that the script can efficiently handle merging large CSV files.

### Example Usage

```python
import csv_merger

# Merge multiple CSV files
csv_merger.merge(['file1.csv', 'file2.csv', 'file3.csv'], output_file='merged_data.csv')

# Customize the output file name
csv_merger.merge(['file1.csv', 'file2.csv', 'file3.csv'], output_file='combined_data.csv')
```
`Difficulty`: Beginner/ Intermediate

`Tags`: Python, CSV, Data Merging, Data Aggregation

### Additional Information
- Consider using libraries like pandas or built-in CSV handling in Python for efficient data processing.
- Ensure that the script provides informative error messages in case of invalid input or other issues during the merging process.

### Contribution Guidelines
The updated guidelines can be found [here](https://github.com/bhargavnova/python-helper-modules#contributing-guidelines).

### Note:
- `folder_name`: merge_csv_files
- `script_name`: merge_csv_files

**Comment by aecuto** [comment]
i'll take this

**Comment by bhargavnova** [comment]
Sure! @aecuto,
Happy to help :)
Please keep in mind the Guidelines.

Thanks
Happy Coding!
