### ISSUE TITLE
Divide Large JSON Files into Small Script/Module

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#40]
### Objective

Develop a Python script or module that allows users to divide large JSON (JavaScript Object Notation) files into smaller, more manageable chunks. This tool will help users process and work with large JSON datasets efficiently.

### Features

- **Chunk Size Specification**: Allow users to specify the desired size of each resulting JSON chunk. (KB, MB....)

- **Output File Naming**: Provide options to customize the naming convention for the generated JSON chunks.

- **Handle Nested JSON**: Ensure that the script can handle cases where the JSON data has nested structures.

- **Preserve Valid JSON**: Guarantee that each generated chunk remains a valid JSON object.

### Example Usage

```python
import json_divider

# Divide a large JSON file into smaller chunks
json_divider.divide('large_data.json', chunk_size=1000, output_folder='output_folder')

# Customize the naming convention for output files
json_divider.divide('large_data.json', chunk_size=500, output_folder='output_folder', custom_names=['part1.json', 'part2.json'])
```

`Difficulty`: Beginner/Intermediate

`Tags`: Python, JSON, Data Processing, Chunking

### Additional Information
- Consider using libraries like json in Python for handling JSON operations.
- Ensure that the script provides informative error messages in case of invalid JSON input or other issues during the dividing process.

### Contribution Guidelines
The updated guidelines can be found [here](https://github.com/bhargavnova/python-helper-modules#contributing-guidelines).

### Note:
- `folder_name`: divide_json
- `script_name`: divide_json

**Comment by aecuto** [comment]
i'll take this

**Comment by bhargavnova** [comment]
Sure!

**Comment by aecuto** [comment]
too hard for me :)

**Comment by bhargavnova** [comment]
okay @aecuto ,
so it will be like a list of dictionaries if any JSON file has lots of rows, 
that can be divided into small batches, that was the concept,
if anyone wants to take over, just comment.

Happy Coding!

**Comment by aecuto** [comment]
the json have many formats such as `[{},{}]` `{keys: []}` `{}`  that why tis too hard

**Comment by bhargavnova** [comment]
as of now, let's go with the first, because that's common when it comes to large file,

**Comment by aecuto** [comment]
lets me try aging :)

**Comment by bhargavnova** [comment]
Hi @aecuto,
Thanks for your contribution,

You can take a look at other open issues or, you can also submit one of your own code/ideas.

Thanks :)
Happy coding!
