### ISSUE TITLE
CSV Data Filter Function/Module

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#46]
### Objective

Develop a Python module that provides a function for filtering data in CSV (Comma Separated Values) files based on user-defined criteria. This module will enable users to specify conditions like column name, filter value, and comparison operators (e.g., equals, not equals) to selectively extract data from CSV files.

### Features

- **Column-based Filtering**: Allow users to filter data based on specific column names.

- **Support for Comparison Operators**: Provide options for users to specify comparison operators like equals, not equals, greater than, less than, etc.

- **Output Options**: Allow users to choose whether to save the filtered data to a new CSV file or return it as a list or DataFrame.

### Example Usage

```python
import csv_filter

# Filter data where 'Age' is greater than 30
filtered_data = csv_filter.filter_csv('data.csv', column='Age', operator='>', value=30)

# Filter data where 'Status' is 'Active'
filtered_data = csv_filter.filter_csv('data.csv', column='Status', operator='==', value='Active')

# Save the filtered data to a new CSV file
csv_filter.save_filtered_data('filtered_data.csv', filtered_data)
```

`Difficulty`: Beginner/Intermediate

`Tags`: Python, CSV, Data Filtering, Data Manipulation

### Additional Information
- Consider using libraries like pandas for efficient data processing and filtering.
- For Beginners, you can use CSV and loops if not comfortable with pandas.
- Ensure that the module provides informative error messages in case of invalid input or other issues during the filtering process.

### Contribution Guidelines
The updated guidelines can be found [here](https://github.com/bhargavnova/python-helper-modules#contributing-guidelines).

### Note:
- `folder_name`: filter_csv
- `script_name`: filter_csv

**Comment by k0msenapati** [comment]
I want to work on this. Please assign me this issue.

**Comment by bhargavnova** [comment]
Sure @kom-senapati ,
Thanks for picking this up!

Happy Coding!
