### ISSUE TITLE
Simple Code Snippet Manager

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#47]
### Objective

Develop a Python module that allows users to manage and store code snippets for easy retrieval. This module will support basic CRUD (Create, Read, Update, Delete) operations, enabling users to add, view, edit, and delete code snippets as needed. (use and files to store the data .csv, .json, .db, etc...

### Features

- **Add New Code Snippet**:
  - Implement functionality to add a new code snippet with a specified title, description, and code content.

- **View Existing Code Snippets**:
  - Allow users to list and view all currently stored code snippets.

- **Edit Code Snippet**:
  - Provide the ability to modify the title, description, or code content of an existing code snippet.

- **Delete Code Snippet**:
  - Enable users to remove a specific code snippet based on its ID or title.

### Example Usage

```python
import code_snippet_manager

# Add a new code snippet
code_snippet_manager.add_snippet('Example Code', 'This is a sample code snippet', 'print("Hello, World!")')

# List existing code snippets
code_snippet_manager.list_snippets()

# Edit an existing code snippet
code_snippet_manager.edit_snippet(1, new_title='Updated Code', new_description='Updated description', new_code='print("Updated Code")')

# Delete a specific code snippet
code_snippet_manager.delete_snippet(2)
```

`Difficulty`: Beginner/Intermediate

`Tags`: Python, Code Snippet Management, CRUD Operations

### Additional Information
- Consider using a data structure like a dictionary or a database to store and manage the code snippets.
- Ensure that the module provides informative error messages in case of invalid input or other issues during the management process.

### Contribution Guidelines
The updated guidelines can be found [here](https://github.com/bhargavnova/python-helper-modules#contributing-guidelines).

### Note:
- `folder_name`: snippet_manager
- `script_name`: snippet_manager

**Comment by k0msenapati** [comment]
I want to work on this issue. Kindly assign this to me.

**Comment by bhargavnova** [comment]
Sure @kom-senapati,
Thanks for picking this up :)

Happy Coding!!

**Comment by bhargavnova** [comment]
Hey @kom-senapati,
Thank you for your contribution :),
You can check more open issues or you can submit one of your own issues.

Happy Coding!
