### ISSUE TITLE
Image Format Converter Python Module 🖼️🔄

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#6]
**Objective**:

Create a Python module that enables users to convert images from one format to another. This module should provide a straightforward way to transform images.

**Features**:

1. **Format Support**:
   - The module should support conversion between popular image formats such as JPEG, PNG, GIF, TIFF, etc.

2. **Simplicity and Efficiency**:
   - Design the module to be easy to use with a minimalistic, allowing users to convert images with a single function call.

**Example Usage**:

```python
import image_converter

# Convert an image from JPEG to PNG format
image_converter.convert_image("/path/to/input_image.webp", "/path/to/output_image.png", "png")
```
Difficulty: Beginner
Tags: Python, Utility, Customization

**Comment by stktyagi** [comment]
Hello, @bhargavnova Can I please work on this issue and get assigned. Thank you!

**Comment by stktyagi** [comment]
Hello, I want contribute and solve this issue for hacktoberfest. Kindly assign this to me. Thanks!

**Comment by bhargavnova** [comment]
Sure!!

**Comment by stktyagi** [comment]
I have completed the code for this issue.

**Comment by bhargavnova** [comment]
Thanks for your contribution : )
