### ISSUE TITLE
Detect Open Ports and Running Services

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#60]
### Objective:

Develop a Python script that can detect all open ports on the local system and list the corresponding running services.

### Features:
- Scan and identify open ports on the local machine.
- Determine the corresponding services or applications associated with each open port.

### Example Usage:

```python
# Example usage of the port detection script
import port_scanner

# Detect open ports and running services
port_scanner.detect_open_ports()
```

`Difficulty`: Beginner/Intermediate

`Tags`: Python, Networking, Scripting

### Additional Information:
- Consider using the `socket` module for port scanning.
- Ensure that the script handles different protocols (TCP/UDP).

### Contribution Guidelines
The updated guidelines can be found [here](https://github.com/bhargavnova/python-helper-modules#contributing-guidelines).

### Note:
- `folder_name`: port_scanner
- `script_name`: port_scanner

**Comment by souravkrishnas** [comment]
Hi @bhargavnova   I think I can work on this. Can you please assign this issue to me.
