### ISSUE TITLE
Find Files by Keywords and Retrieve Information

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#61]
### Objective:
Develop a Python script that can search for files containing specific keywords in a specified directory and provide certain information about those files.

### Features:
- Search for files in a specified directory.
- Filter files based on specific keywords.
- Retrieve and display relevant information about the matched files.

### Example Usage:

```python
# Example usage of the file finder script
import file_finder

# Specify the directory and keywords
directory_path = "/path/to/directory"
keywords = ["keyword1", "keyword2", "keyword3"]

# Find files and retrieve information
file_finder.find_files_by_keywords(directory_path, keywords)
```

`Difficulty`: Beginner/Intermediate

`Tags`: Python, File Handling, Scripting

### Additional Information:
- Consider using the `os` module for file operations and content search.
- Provide options for case-insensitive search and handling subdirectories.

### Contribution Guidelines
The updated guidelines can be found [here](https://github.com/bhargavnova/python-helper-modules#contributing-guidelines).

### Note:
- `folder_name`: file_finder
- `script_name`: file_finder

**Comment by lavanderhoney** [comment]
Hello @bhargavnova , I have a fair bit of experience in python and am very confident about solving this. Can you please assign this issue to me?

**Comment by bhargavnova** [comment]
Sure @lavanderhoney :)
Happy Coding!

**Comment by lavanderhoney** [comment]
I have a question @bhargavnova. What information should be returned for a matched file? Like should it return at what index the word is found or how many keywords are found in that file?

**Comment by bhargavnova** [comment]
Hi @lavanderhoney,
any information will do, like file location, name, last modified, etc.. your choice.
