### ISSUE TITLE
Get List of Recently Accessed Files

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#62]
### Objective:

Develop a Python script that retrieves a list of recently accessed files on the local system.

### Features:

- Identify and list files based on their recent access timestamps.
- Provide options for specifying a directory or searching system-wide.
- Display information such as file names, paths, and access timestamps.

### Example Usage:

```python
# Example usage of the script to get recently accessed files
import recently_accessed_files

# Retrieve list of recently accessed files
recently_accessed_files.get_recently_accessed_files()
```

`Difficulty`: Beginner/Intermediate

`Tags`: Python, File Handling, Scripting

### Additional Information:
- Consider using the `os` module for file operations and `os.path.getatime()` to retrieve access times.
- Provide options for setting a time threshold for 'recent' accesses.

### Contribution Guidelines
The updated guidelines can be found [here](https://github.com/bhargavnova/python-helper-modules#contributing-guidelines).

### Note:
- `folder_name`: recently_accessed_files
- `script_name`: recently_accessed_files

**Comment by onkar-kota** [comment]
Hi @bhargavnova in this issue ... we have to access list  of files from specific directory or system-wide?

**Comment by bhargavnova** [comment]
@onkar-kota,

Well, that will be efficient when it's systemwide, but that will involve more complex code because systems have lots of files.
let's aim for a directory now, because the whole system is itself a directory.
time to get that list will increase if directory size/I mean file count increases,

so work like aiming for the directory,
if you want I can assign this one to you.

**Comment by onkar-kota** [comment]
@bhargavnova 
Yeah, that's true... the code will be bit more complex.
Yes, assign me I'll try to resolve this issue

**Comment by bhargavnova** [comment]
cool!
happy coding!

**Comment by onkar-kota** [comment]
Hey @bhargavnova please check my PR #67
