### ISSUE TITLE
Configuration file manager module

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#64]

**Comment by harshjais369** [comment]
Hey @bhargavnova , thanks for letting me work on this issue and become part of this community. I've raised a PR #65 for this issue, please check it at your convenience time and let me know if it still requires any adjustments. Once we both are done on this, I would request you to lable my PR to hacktoberfest-accepted.

**Comment by bhargavnova** [comment]
Sure! @harshjais369,
no need for a label, because the repo has hacktoberfest label,

Thanks for your contribution :),
You can work on other open issues or you can also submit your own code.

Happy Coding!
