### ISSUE TITLE
Local Network Device Discovery Script 🌐🔍

### ISSUE THREAD

**Issue by bhargavnova** [bhargavnova/python-helper-modules#8]
**Objective**:

Create a Python script to discover devices on a local network. This script will send ARP requests to obtain information about active devices.

**Features**:

1. **Device Discovery**:
   - Implement a function to send ARP requests to all devices on the local network.

2. **Information Retrieval**:
   - Retrieve and display the IP and MAC addresses of discovered devices.

3. **User-Friendly Output**:
   - Present the information in a clear and easy-to-read format.
   - or just return a list of dictionaries that contain discovered information. 

**Example Usage**:

```python
# Example usage of the local network device discovery script
import network_discovery

devices = network_discovery.discover_devices("192.168.0.1/24")
```
**Difficulty**: Beginner/Intermediate
**Tags**: Python, Utility, Networking

**Additional Information**:

- Familiarity with networking concepts and Python scripting is recommended for contributors taking on this task.
- **Important**---**Ensure to obtain proper authorization before conducting any network scanning.**

**Comment by chankruze** [comment]
Assign it to me @bhargavnova
